export const users ={
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    LOGOUT: 'USERS_LOGOUT',

    FETCH_MEAL_PENDING_BY_NAME : "FETCH_MEAL_PENDING_BY_NAME",
    FETCH_MEAL_SUCCESS_BY_NAME : "FETCH_MEAL_SUCCESS_BY_NAME",
    FETCH_MEAL_ERROR_BY_NAME : "FETCH_MEAL_ERROR_BY_NAME",
    FETCH_MEAL_NOTFOUND :"FETCH_MEAL_NOTFOUND",

    
}