export const users ={
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    LOGOUT: 'USERS_LOGOUT',

    FETCH_MEAL_PENDING_BY_NAME : "FETCH_MEAL_PENDING_BY_NAME",
    FETCH_MEAL_SUCCESS_BY_NAME : "FETCH_MEAL_SUCCESS_BY_NAME",
    FETCH_MEAL_ERROR_BY_NAME : "FETCH_MEAL_ERROR_BY_NAME",
    FETCH_MEAL_NOTFOUND :"FETCH_MEAL_NOTFOUND",

    // ingredient
    FETCH_MEAL_BY_INGREDIENT_PEANDING :"FETCH_MEAL_BY_INGREDIENT_PEANDING",
    FETCH_MEAL_BY_INGREDIENT_SUCCESS:"FETCH_MEAL_BY_INGREDIENT_SUCCESS",
    FETCH_MEAL_BY_INGREDIENT_ERROR:"FETCH_MEAL_BY_INGREDIENT_ERROR",
    FETCH_MEAL_BY_INGREDIENT_NOTFOUND:"FETCH_MEAL_BY_INGREDIENT_NOTFOUND",

    //  list ingredient
    FETCH_LIST_OF_INGRENDIENT_PENDING:"FETCH_LIST_OF_INGRENDIENT_PENDING",
    FETCH_LIST_OF_INGRENDIENT_SUCCESS:"FETCH_LIST_OF_INGRENDIENT_SUCCESS",
    FETCH_LIST_OF_INGRENDIENT_ERROR:"FETCH_LIST_OF_INGRENDIENT_ERROR",
    FETCH_LIST_OF_INGRENDIENT_NOTFOUND:"FETCH_LIST_OF_INGRENDIENT_NOTFOUND",

    // LIST OF AREA
    FETCH_LIST_OF_AREA_PENDING:"FETCH_LIST_OF_AREA_PENDING",
    FETCH_LIST_OF_AREA_SUCCESS:"FETCH_LIST_OF_AREA_SUCCESS",
    FETCH_LIST_OF_AREA_ERROR:"FETCH_LIST_OF_AREA_ERROR",
    FETCH_LIST_OF_AREA_NOTFOUND:"FETCH_LIST_OF_AREA_NOTFOUND",

    // LIST OF CATEGORY

    FETCH_LIST_OF_CATEGORY_PENDING:"FETCH_LIST_OF_CATEGORY_PENDING",
    FETCH_LIST_OF_CATEGORY_SUCCESS:"FETCH_LIST_OF_CATEGORY_SUCCESS",
    FETCH_LIST_OF_CATEGORY_ERROR:"FETCH_LIST_OF_CATEGORY_ERROR",
    FETCH_LIST_OF_CATEGORY_NOTFOUND:"FETCH_LIST_OF_CATEGORY_NOTFOUND",

    // letter api

    FETCH_LIST_OF_LETTER_PENDING:"FETCH_LIST_OF_LETTER_PENDING",
    FETCH_LIST_OF_LETTER_SUCCESS:"FETCH_LIST_OF_LETTER_SUCCESS",
    FETCH_LIST_OF_LETTER_ERROR:"FETCH_LIST_OF_LETTER_SUCCESS",
    FETCH_LIST_OF_LETTER_NOTFOUND:"FETCH_LIST_OF_LETTER_NOTFOUND",
    
    // ID
    FETCH_MEAL_BY_ID_PENDING:"FETCH_MEAL_BY_ID_PENDING",
    FETCH_MEAL_BY_ID_SUCCESS:"FETCH_MEAL_BY_ID_SUCCESS",
    FETCH_MEAL_BY_ID_ERROR:"FETCH_MEAL_BY_ID_ERROR",

    // ingerditent meal
    FETCH_MEAL_BY_INGERDIENT_PENDING:"FETCH_MEAL_BY_INGERDIENT_PENDING",
    FETCH_MEAL_BY_INGERDIENT_SUCCESS:"FETCH_MEAL_BY_INGERDIENT_SUCCESS",
    FETCH_MEAL_BY_INGERDIENT_ERROR:"FETCH_MEAL_BY_INGERDIENT_ERROR",
    
    
    
}